import postgres from "postgres"
import sql from "../db-pool"
import type { DBExecutor } from "./actor"
import { normalizeId } from "./helpers"

// Announcements the shop writes, and the per-customer read state that turns
// them into an inbox. See migration 103 for why there is no recipient table.

export type Announcement = {
  id: number
  title: string
  body: string
  createdAt: string
  /** 'notice' — the shop wrote it. 'shipping' — a parcel moved. */
  kind: AnnouncementKind
}

export type AnnouncementKind = "notice" | "shipping"


/** An announcement as one customer sees it. */
export type CustomerAnnouncement = Announcement & { read: boolean }

/**
 * Staff view: what the shop wrote, newest first.
 *
 * Automatic shipping notices are excluded. They are addressed to one customer
 * and generated by the hundred; mixed into this list they would bury the
 * handful of announcements a person actually composed.
 */
export async function listAnnouncements(db: DBExecutor = sql): Promise<Announcement[]> {
  const rows = await db<
    { id: number; title: string; body: string; created_at: Date; kind: AnnouncementKind }[]
  >`
    SELECT id, title, body, created_at, kind
      FROM announcements
     WHERE kind = 'notice'
     ORDER BY created_at DESC, id DESC
  `
  return rows.map(toAnnouncement)
}

/**
 * Tell one customer that her parcel moved.
 *
 * Deliberately quiet when the handle matches no customer row: a notice is a
 * courtesy, and a shipment must not fail because the person it belongs to was
 * never registered. Runs on whatever executor it is given, so the notice lands
 * in the same transaction as the shipment that caused it — either both happen
 * or neither does.
 */
export async function notifyCustomer(
  handle: string,
  notice: { title: string; body: string },
  db: DBExecutor = sql,
): Promise<void> {
  const key = normalizeId(handle)
  await db`
    INSERT INTO announcements (title, body, kind, customer_id)
    SELECT ${notice.title}, ${notice.body}, 'shipping', c.id
      FROM customers c
     WHERE lower(replace(c.instagram_id, '@', '')) = ${key}
  `
}

/**
 * Who a notice about one trip would reach.
 *
 * There were two shapes and nothing between them: an announcement with no
 * customer_id, which every customer sees, and notifyCustomer, which reaches
 * exactly one. A cargo delay on one trip is neither -- telling everybody
 * includes people with no order on it, and telling them one at a time is forty
 * invoices opened by hand.
 *
 * `skipShipped` leaves out anyone whose every unit has already gone. Their
 * parcel is not in that cargo, and a delay notice they cannot act on is a false
 * alarm that costs the next real one its credibility.
 */
export async function eventNoticeRecipients(
  event: string,
  skipShipped = true,
  db: DBExecutor = sql,
): Promise<{ customer: string; units: number; unshipped: number }[]> {
  const rows = await db<{ customer: string; units: string; unshipped: string }[]>`
    SELECT c.instagram_id AS customer,
           SUM(o.unit)::int AS units,
           SUM(GREATEST(o.unit - COALESCE(o.unit_ship, 0), 0))::int AS unshipped
      FROM orders o
      JOIN customers c
        ON lower(replace(c.instagram_id, '@', '')) = lower(replace(o.customer, '@', ''))
     WHERE o.event = ${event}
       AND o.unit > 0
     GROUP BY c.instagram_id
     ORDER BY c.instagram_id
  `
  return rows
    .map((r) => ({ customer: r.customer, units: Number(r.units), unshipped: Number(r.unshipped) }))
    .filter((r) => (skipShipped ? r.unshipped > 0 : true))
}

/**
 * One notice, to everybody on one trip.
 *
 * Personal rows rather than a single global one: it belongs in the inbox of the
 * people it is about and nobody else's, and read state is per person -- one
 * shared row would be read by the first customer to open it and unread for the
 * rest, or worse, the other way round.
 *
 * Written in one statement so a delay notice cannot reach half a trip.
 */
export async function notifyEventCustomers(
  event: string,
  notice: { title: string; body: string },
  opts: { skipShipped?: boolean } = {},
  db: DBExecutor = sql,
): Promise<{ sent: number; customers: string[] }> {
  const recipients = await eventNoticeRecipients(event, opts.skipShipped ?? true, db)
  if (recipients.length === 0) return { sent: 0, customers: [] }

  const keys = recipients.map((r) => r.customer)
  await db`
    INSERT INTO announcements (title, body, kind, customer_id)
    SELECT ${notice.title.trim()}, ${notice.body.trim()}, 'shipping', c.id
      FROM customers c
     WHERE c.instagram_id = ANY(${keys})
  `
  return { sent: keys.length, customers: keys }
}

export async function createAnnouncement(
  data: { title: string; body: string },
  db: DBExecutor = sql,
): Promise<Announcement> {
  const [row] = await db<{ id: number; title: string; body: string; created_at: Date }[]>`
    INSERT INTO announcements (title, body)
    VALUES (${data.title.trim()}, ${data.body.trim()})
    RETURNING id, title, body, created_at
  `
  return toAnnouncement(row)
}

export async function updateAnnouncement(
  id: number,
  data: { title: string; body: string },
  db: DBExecutor = sql,
): Promise<void> {
  await db`
    UPDATE announcements
       SET title = ${data.title.trim()}, body = ${data.body.trim()}, updated_at = NOW()
     WHERE id = ${id}
  `
}

/** Deleting takes its read rows with it, via ON DELETE CASCADE. */
export async function deleteAnnouncement(id: number, db: DBExecutor = sql): Promise<void> {
  await db`DELETE FROM announcements WHERE id = ${id}`
}

/**
 * One customer's inbox, newest first.
 *
 * A missing read row means unread, so nothing is written when an announcement
 * is published — only when someone opens it. A customer who signs up tomorrow
 * therefore sees today's announcement as unread, which is right: it is new to
 * them.
 *
 * `db` must be the scoped catalogue_public connection on the public path.
 */
export async function listAnnouncementsForCustomer(
  customerId: number,
  db: postgres.Sql | DBExecutor = sql,
): Promise<CustomerAnnouncement[]> {
  const rows = await db<
    { id: number; title: string; body: string; created_at: Date; kind: AnnouncementKind; read: boolean }[]
  >`
    SELECT a.id, a.title, a.body, a.created_at, a.kind,
           (r.customer_id IS NOT NULL) AS read
      FROM announcements a
      LEFT JOIN announcement_reads r
        ON r.announcement_id = a.id AND r.customer_id = ${customerId}
     WHERE a.customer_id IS NULL OR a.customer_id = ${customerId}
     ORDER BY a.created_at DESC, a.id DESC
  `
  return rows.map((r) => ({ ...toAnnouncement(r), read: r.read }))
}

/**
 * Mark every announcement read for this customer.
 *
 * Written as "insert what is missing" rather than a list of ids from the
 * client: the set the customer just saw is whatever exists now, and taking
 * ids from the request would let a caller mark rows it was never shown. ON
 * CONFLICT keeps a second open from failing.
 */
export async function markAnnouncementsRead(
  customerId: number,
  db: postgres.Sql | DBExecutor = sql,
): Promise<void> {
  await db`
    INSERT INTO announcement_reads (announcement_id, customer_id)
    SELECT a.id, ${customerId} FROM announcements a
     WHERE a.customer_id IS NULL OR a.customer_id = ${customerId}
    ON CONFLICT (announcement_id, customer_id) DO NOTHING
  `
}

function toAnnouncement(r: {
  id: number
  title: string
  body: string
  created_at: Date
  kind?: AnnouncementKind
}): Announcement {
  return {
    id: r.id,
    title: r.title,
    body: r.body,
    createdAt: r.created_at.toISOString(),
    kind: r.kind ?? "notice",
  }
}
