// Barrel for the data-access layer. Implementation lives in ./db/*.
// Existing imports `from "@/lib/db"` keep working unchanged.
export * from "./db/actor"
export * from "./db/helpers"
export * from "./db/types"
export * from "./db/orders"
export * from "./db/customers"
export * from "./db/invoice"
export * from "./db/fulfillment"
export * from "./db/catalog"
export * from "./db/catalogue-highlights"
export * from "./db/catalogue-posts"
export * from "./db/catalogue-requests"
export * from "./db/finance"
export * from "./db/operational-expenses"
export * from "./db/shopping-list"
export * from "./db/dispatch"
export * from "./db/dashboard"
export * from "./db/settings"
