-- Add created_at and updated_at to tables that are missing them.

ALTER TABLE countries ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE countries ADD COLUMN updated_at TIMESTAMPTZ;

ALTER TABLE events ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE events ADD COLUMN updated_at TIMESTAMPTZ;

ALTER TABLE customers ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE customers ADD COLUMN updated_at TIMESTAMPTZ;

ALTER TABLE products ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE products ADD COLUMN updated_at TIMESTAMPTZ;

ALTER TABLE products_indo ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE products_indo ADD COLUMN updated_at TIMESTAMPTZ;
